name: Deploy Datahub Client V2

# Trigger on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x 

      # 3. Install dependencies
      - name: Install npm packages
        run: npm ci

      # 4. Build Angular production
      - name: Build Angular production
        run: npx ng build --configuration production

      # 5. Copy .htaccess to dist
      - name: Copy .htaccess
        run: cp .htaccess dist/datahub_app_v2/browser/.htaccess

      # 6. Copy files to remote server
      - name: Copy files to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            rm -rf *
      
      # 7. Copy files to remote server
      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: dist/datahub_app_v2/browser/.
          target: ${{ secrets.SERVER_PATH }}
          strip_components: 3
